### ISSUE TITLE
s32ds version

### ISSUE THREAD

**Issue by liker292** [xueshawu/S32K144#1]
which version of s32ds ,to build the project?

**Comment by xueshawu** [comment]
S32 Design Studio for ARM Version: 2.0 ，I’m so sorry,this project isn't commit completed,i will commit again in this weekend

**Comment by xueshawu** [comment]
S32 Design Studio for ARM Version: 2.0 ，I’m so sorry,this project isn't commit completed,i will commit again in this weekend
